name: Security Pipeline

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main
      - feature/**

jobs:
  setup:
    name: Repository Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Display Node Version
        run: node -v

      - name: Display npm Version
        run: npm -v

  semgrep:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
    needs: setup

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Semgrep
        uses: semgrep/semgrep-action@v1
        with:
          config: p/security-audit

  trufflehog:
    name: TruffleHog Secret Scan
    runs-on: ubuntu-latest

    needs: setup

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ""
          head: HEAD

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest

    needs:
      - semgrep
      - trufflehog

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: plantu-ai:latest

  trivy:
    name: Trivy Image Scan

    runs-on: ubuntu-latest

    needs:
      - docker-build

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          push: false
          tags: plantu-ai:latest

      - name: Run Trivy Image Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: plantu-ai:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH